# Generated by Django 5.1.4 on 2025-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_token_date', models.TimeField(auto_now=True)),
            ],
        ),
    ]
