# Generated by Django 5.1.4 on 2025-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='user_ip_address',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
