# Generated by Django 5.1.4 on 2025-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usertoken_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='user_ip_address',
            field=models.CharField(max_length=64),
        ),
    ]
