# Generated by Django 5.1.4 on 2025-01-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('download_time', models.TimeField(auto_now=True)),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertoken')),
            ],
        ),
    ]
